name: Python application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linter (flake8)
      run: |
        flake8 .
      continue-on-error: true  # Allows the workflow to continue even if flake8 finds issues

    - name: Run formatter (black)
      run: |
        black .
      continue-on-error: false  # Ensures the workflow fails if black cannot format the code

    - name: Run tests
      run: |
        pytest --html=report.html

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.html
